### PR TITLE
Adding publish/subscriber api wrapper for dapr

### PR DESCRIPTION
**Pull request by SAtacker**

### CODE REVIEW

**Comment by SAtacker** [comment]
@juntao can you please let me know your thoughts?

**Comment by juntao** [comment]
Can you create a GitHub Actions CI test for this in the `.github/workflows/main.yml` file? 

You can use `hyper` to create a HTTP webhook service that listens for new messages on a topic? Example: https://github.com/WasmEdge/wasmedge_hyper_demo/tree/main/server

Thanks.

**Comment by SAtacker** [comment]
> Can you create a GitHub Actions CI test for this in the `.github/workflows/main.yml` file?

Yes, i'll do it.

> You can use `hyper` to create a HTTP webhook service that listens for new messages on a topic? Example: https://github.com/WasmEdge/wasmedge_hyper_demo/tree/main/server

Alright, thanks.

**Comment by SAtacker** [comment]
> > Can you create a GitHub Actions CI test for this in the `.github/workflows/main.yml` file?
> 
> Yes, i'll do it.
> 
> > You can use `hyper` to create a HTTP webhook service that listens for new messages on a topic? Example: https://github.com/WasmEdge/wasmedge_hyper_demo/tree/main/server
> 
> Alright, thanks.
> 
> 
> 

I have added the subscriber within the echo app itself. Also added a print statement to make it a bit more verbose.
Can you PTAL?

**Comment by juntao** [comment]
> I have added the subscriber within the echo app itself. Also added a print statement to make it a bit more verbose. Can you PTAL?

That is a great idea and it looks good.

Can you add a test case in the CI and we can merge? Thanks.

**Comment by SAtacker** [comment]
@juntao can we merge this for now?

**Comment by SAtacker** [comment]
Closing this in favour of #4

**Pull request closed without merging**
